### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Edward-Young1990** [Yang-Xijie/mkv2mp4_fcp#2]
I can only get the three files:
1.flac
1.h265
1.m4a

Then got error below.
[HEVC] Error parsing Video Param Set
[HEVC] sorry, 23 layers in VPS but only 4 supported
[HEVC] Warning: Error parsing NAL unit

Any hint will be helpful.
Thank you very much!
<img width="1476" alt="code run" src="https://user-images.githubusercontent.com/64726945/101504442-2f902280-39ae-11eb-90b6-169599776169.png">
<img width="1476" alt="error happen" src="https://user-images.githubusercontent.com/64726945/101504469-35860380-39ae-11eb-91fe-522ca2d0e62f.png">

**Comment by Yang-Xijie** [comment]
Hi, some information might be ignored by you.

At the beginning of my script I wrote:

```shell
# Functions: Convert anime(with mkv format, track 0 hevc, track 1 flac) to mp4 to make it importable to FCP without recoding .
```

You should first confirm that `your mkv file` has video codec **hevc on track 0** and audio codec **flac on track 1**. Use `mkvinfo` to check the track info of `your mkv file`. In your screenshot, you regard h264 as hevc and DTS as flac so the script not worked.

**Comment by Yang-Xijie** [comment]
If you are not familiar with video transcoding, I recommend you learn something about it. Or you could use some apps like Permute 3 on macOS to automatically transcode these media.

**Comment by Edward-Young1990** [comment]
Good Evening!
Thank you for your quick&professional reply.
It helps a lot. I'll check it and try it again.
And thanks for your app recommended.
The programmer make the world better, I do believe so.
Thank you again!!!

**Comment by Yang-Xijie** [comment]
Thanks ,too. That's the first time I have interacted with someone in issue!
